src/Domain/Course/Entity/Formation.php
<?php

namespace App\Domain\Course\Entity;

use App\Domain\Application\Entity\Content;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Domain\Course\Repository\FormationRepository")
 */
class Formation extends Content
{
    use LevelTrait;
    use ChapterableTrait;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $short = null;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $youtube_playlist = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Domain\Course\Entity\Course", mappedBy="formation")
     *
     * @var Collection<int, Course>
     */
    private $courses;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private ?string $links = null;

    public function __construct()
    {
        $this->courses = new ArrayCollection();
        parent::__construct();
    }

    public function getShort(): ?string
    {
        return $this->short;
    }

    public function setShort(?string $short): self
    {
        $this->short = $short;

        return $this;
    }

    public function getDuration(): int
    {
        return array_reduce($this->courses->toArray(), function (int $acc, Course $item) {
            $acc += $item->getDuration();

            return $acc;
        }, 0);
    }

    public function getYoutubePlaylist(): ?string
    {
        return $this->youtube_playlist;
    }

    public function setYoutubePlaylist(?string $youtube_playlist): self
    {
        $this->youtube_playlist = $youtube_playlist;

        return $this;
    }

    public function getNextCourseId(?int $id): ?int
    {
        if (null === $id) {
            return null;
        }
        $ids = array_reduce($this->getRawChapters(), fn ($acc, $chapter) => array_merge($acc, $chapter['modules']), []);
        $index = array_search($id, $ids);
        if (false === $index) {
            return null;
        }

        return $ids[(int) $index + 1] ?? null;
    }

    /**
     * @return Collection<int, Course>
     */
    public function getCourses(): Collection
    {
        return $this->courses;
    }

    public function addCourse(Course $course): self
    {
        if (!$this->courses->contains($course)) {
            $this->courses[] = $course;
            $course->setFormation($this);
        }

        return $this;
    }

    public function removeCourse(Course $course): self
    {
        if ($this->courses->contains($course)) {
            $this->courses->removeElement($course);
            // set the owning side to null (unless already changed)
            if ($course->getFormation() === $this) {
                $course->setFormation(null);
            }
        }

        return $this;
    }

    public function getCoursesById(): array
    {
        $courses = $this->getCourses();
        $coursesById = [];
        foreach ($courses as $course) {
            $coursesById[$course->getId()] = $course;
        }

        return $coursesById;
    }

    public function getLinks(): ?string
    {
        return $this->links;
    }

    public function setLinks(?string $links): self
    {
        $this->links = $links;

        return $this;
    }
}

src/Http/Admin/Controller/FormationController.php
<?php

namespace App\Http\Admin\Controller;

use App\Domain\Application\Event\ContentCreatedEvent;
use App\Domain\Application\Event\ContentDeletedEvent;
use App\Domain\Application\Event\ContentUpdatedEvent;
use App\Domain\Course\Entity\Formation;
use App\Http\Admin\Data\FormationCrudData;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/formation", name="formation_")
 *
 * @method getRepository() App\Domain\Formation\$formation\$formation\Forma
 */
final class FormationController extends CrudController
{
    protected string $templatePath = 'formation';
    protected string $menuItem = 'formation';
    protected string $entity = Formation::class;
    protected string $routePrefix = 'admin_formation';
    protected array $events = [
        'update' => ContentUpdatedEvent::class,
        'delete' => ContentDeletedEvent::class,
        'create' => ContentCreatedEvent::class,
    ];

    /**
     * @Route("/", name="index")
     */
    public function index(): Response
    {
        $this->paginator->allowSort('row.id');
        $query = $this->getRepository()
            ->createQueryBuilder('row')
            ->leftJoin('row.technologyUsages', 'tu')
            ->leftJoin('tu.technology', 't')
            ->addSelect('t', 'tu')
            ->orderby('row.createdAt', 'DESC')
        ;

        return $this->crudIndex($query);
    }

    /**
     * @Route("/new", name="new", methods={"POST", "GET"})
     */
    public function new(): Response
    {
        $entity = (new Formation())->setAuthor($this->getUser());
        $data = new FormationCrudData($entity);

        return $this->crudNew($data);
    }

    /**
     * @Route("/{id<\d+>}", name="edit", methods={"POST", "GET"})
     */
    public function edit(Formation $formation): Response
    {
        $data = (new FormationCrudData($formation))->setEntityManager($this->em);

        return $this->crudEdit($data);
    }

    /**
     * @Route("/{id<\d+>}", methods={"DELETE"})
     */
    public function delete(Formation $formation): Response
    {
        return $this->crudDelete($formation);
    }
}

src/Http/Controller/Course/FormationController.php
<?php

namespace App\Http\Controller\Course;

use App\Domain\Course\Entity\Course;
use App\Domain\Course\Entity\Formation;
use App\Domain\Course\Entity\Technology;
use App\Domain\Course\Repository\FormationRepository;
use App\Domain\History\HistoryService;
use App\Domain\History\Repository\ProgressRepository;
use App\Http\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class FormationController extends AbstractController
{
    /**
     * @Route("/formations", name="formation_index")
     */
    public function index(FormationRepository $formationRepository): Response
    {
        $formations = $formationRepository->findAll();

        return $this->render('formations/index.html.twig', [
            'formations' => $formations,
            'menu' => 'formations',
        ]);
    }

    /**
     * @Route("/cursus", name="cursus_index")
     */
    public function tree(EntityManagerInterface $em): Response
    {
        $technologies = $em->getRepository(Technology::class)->findBy([
            'slug' => ['php', 'ruby', 'nodejs', 'laravel', 'symfony', 'react', 'vuejs'],
        ]);
        $formations = collect($em->getRepository(Formation::class)->findBy([
            'slug' => [
                'php',
                'debuter-javascript',
                'css',
                'html',
                'webpack',
                'vuejs',
                'mysql',
                'git',
                'apprendre-algorithmique',
                'programmation-objet-php',
                'ruby-on-rails',
                'ruby',
                'nodejs',
                'laravel',
                'symfony-4-pratique',
                'upload-site',
                'react',
            ],
        ]))->keyBy(fn (Formation $f) => $f->getSlug())->toArray();

        return $this->render('formations/tree.html.twig', [
            'formations' => $formations,
            'technologies' => $technologies,
            'menu' => 'cursus',
        ]);
    }

    /**
     * @Route("/formations/{slug}", name="formation_show")
     */
    public function show(
        Formation $formation,
        ProgressRepository $progressRepository
    ): Response {
        $user = $this->getUser();
        $progress = null;
        if ($user) {
            $progress = $progressRepository->findOneByContent($user, $formation);
        }

        return $this->render('formations/show.html.twig', [
            'formation' => $formation,
            'menu' => 'formations',
            'progress' => $progress,
        ]);
    }

    /**
     * Redirige vers le prochain chapitre à regarder.
     *
     * @Route("/formations/{slug}/continue", name="formation_resume")
     */
    public function resume(
        Formation $formation,
        HistoryService $historyService,
        EntityManagerInterface $em,
        NormalizerInterface $normalizer
    ): RedirectResponse {
        $user = $this->getUser();
        $ids = $formation->getModulesIds();
        $nextContentId = $ids[0];
        if (null !== $user) {
            $nextContentId = $historyService->getNextContentIdToWatch($user, $formation) ?: $ids[0];
        }
        $content = $em->find(Course::class, $nextContentId);
        /** @var array $path */
        $path = $normalizer->normalize($content, 'path');

        return $this->redirectToRoute($path['path'], $path['params']);
    }
}

templates/formations/_card-large.html.twig
{% cache [formation] %}
  <div data-history="{{ formation.id }}">
    <article class="card" data-history="{{ formation.id }}">
      <div class="card__body stack">

        <h2 class="card__title">
          <a href="{{ path('formation_show', {slug: formation.slug}) }}" tabindex="-1">
            {{ formation.title }}
          </a>
        </h2>

        <div class="card__description text-small">
          <p>{{ formation.content | markdown | striptags | excerpt(130) }}</p>
        </div>
        <a href="{{ path('formation_show', {slug: formation.slug}) }}" title="{{ formation.title }}"
           class="card__link"></a>
      </div>
      <footer class="card__footer">
        <div>{{ icon('lines', 12) }} {{ formation.courses | length }} Chapitres</div>
        <div>{{ icon('clock', 14) }} {{ formation.duration | duration }}</div>
      </footer>
    </article>
  </div>
{% endcache %}

templates/formations/_card.html.twig
{% cache [formation] %}
  <article class="card card--stacked" data-history="{{ formation.id }}">
    <div class="card__body stack">
      <div class="card__icons">
        {% for technology in formation.mainTechnologies %}
          <a href="{{ path('technology_show', {slug: technology.slug}) }}" class="course__icon" tabindex="-1">
            <img src="{{ uploads_path('icons/' ~ technology.image) }}" alt="{{ technology.name }}">
          </a>
        {% endfor %}
      </div>

      <h2 class="card__title" style="margin-bottom: 4px;">
        <a href="{{ path('formation_show', {slug: formation.slug}) }}" tabindex="-1">
          {{ formation.title }}
        </a>
      </h2>

      <div class="card__description text-small">
        <p>
          {{ formation.short | markdown | striptags | excerpt(130) | raw }}
        </p>
      </div>
      <a href="{{ path('formation_show', {slug: formation.slug}) }}" title="{{ formation.title }}"
         class="card__link"></a>
    </div>
    <div class="card__progress"><span></span></div>
    <footer class="card__footer">
      <div>{{ icon('lines', 12) }} {{ formation.courses | length }} Chapitres</div>
      <div>{{ icon('clock', 14) }} {{ formation.duration | duration }}</div>
    </footer>
  </article>
{% endcache %}

templates/formations/_tree-card.html.twig
{% set formation = formations[slug] %}
<div class="tree-item {{ cls is defined ? cls : '' }}" id="i{{ slug }}">
  <a href="{{ path(formation) }}" class="tree-item__title">{{ formation.title }}</a>
  <a href="{{ path(formation) }}" class="tree-item__link">Voir la formation</a>
  <div class="tree-item__body">{{ formation.short }}</div>
    {% for technology in formation.mainTechnologies %}
      {% if loop.last %}
      <a href="{{ path(formation) }}" class="tree-item__icon">
        <img src="{{ uploads_path('icons/' ~ technology.image) }}" alt="{{ technology.name }}">
      </a>
      {% endif %}
    {% endfor %}
</div>

templates/formations/index.html.twig
{% extends 'base.html.twig' %}

{% set bodyClass = 'header-light' %}
{% block title 'Toutes les formations' %}

{% block body %}

  <main class="formations split-background container py5" style="--split:380px">
    <div class="course-hero">
      <h1>Toutes les <strong>formations</strong></h1>
      <div>
        <p class="mb1">
          Découvrez une technologie spécifique à travers une série de vidéo qui vous guidera dans votre apprentissage
        </p>
      </div>
    </div>
    {% for formation in formations %}
      {% include 'formations/_card.html.twig' %}
    {% endfor %}
  </main>

  {% if app.user %}
    {{ show_history(formations) }}
  {% endif %}
{% endblock %}

templates/formations/show.html.twig
{% extends 'base.html.twig' %}

{% block title "Formation " ~ formation.title %}

{% block body %}

  {% set first_course = formation.firstContent %}

  <header class="wave-header">
    <div>
      {{ breadcrumb(formation) }}
      <div class="wave-header__body stack">
        <h1 class="wave-header__title">{{ formation.title }}</h1>
        {% if formation.short %}
          <p>{{ formation.short }}</p>
        {% else %}
          {{ formation.content | markdown }}
        {% endif %}
        {% if progress %}
          <div class="formation-progress my3">
            <div class="formation-progress__label">Ma progression</div>
            <div class="formation-progress__count">
              Chapitre {{ (progress.ratio * (formation.courses | length)) | round(0, 'floor') }}
              / {{ formation.courses | length }}</div>
            <div class="formation-progress__bar" style="--progress: {{ progress.ratio * 100 }}%"></div>
          </div>
          <p>
            <a href="{{ path('formation_resume', {slug: formation.slug}) }}#autoplay"
               class="btn-white-outlined btn-big">{{ icon('play') }} Continuer</a>
          </p>
        {% elseif formation.firstContent %}
          <p>
            <a href="{{ path(first_course) }}#autoplay" class="btn-white-outlined btn-big">{{ icon('play') }}
              Commencer</a>
          </p>
        {% endif %}
      </div>
    </div>
    {% if formation.mainTechnologies is not empty %}
      <div class="wave-header__image">
        <img src="{{ uploads_path('icons/' ~ formation.mainTechnologies[0].image) }}" alt="">
      </div>
    {% endif %}
    <waves-shape class="waves" position="bottomWave" target=".wave-header"></waves-shape>
  </header>

  {% cache [formation, app.user and app.user.premium] %}

    <main class="formation-single pb5">
      <div class="formation-chapters">
        <h2 class="h2 mb3">Chapitres</h2>
        {% include 'chapters/_summary.html.twig' with {chapters: formation.chapters, class: 'chapters-split'} only %}
      </div>
      <div class="formation-summary">
        <h2 class="h2 mb3">Présentation</h2>
        {% for technology in formation.mainTechnologies %}
          {% if technology.slug == 'symfony' %}
          <alert-message type="info">
            Cette formation n'est pas officiellement supportée par <a href="https://sensiolabs.com/" target="_blank">SensioLabs</a>.<br>
            Si vous êtes intéréssé·e par des formations officielles, rendez vous sur <a href="https://training.sensiolabs.com/fr/" target="_blank">SensioLabs University
          </alert-message>
          {% endif %}
        {% endfor %}
        <div class="stack" style="--gap:4">
          <div>
            <div>
              <div class="formatted">
                {{ formation.content | markdown }}
              </div>
              <admin-edit hidden></admin-edit>
              <div class="text-muted mt2">
                {{ formation.createdAt | ago }}
              </div>
            </div>
          </div>
          <div class="formation-arguments">
            {% if formation.links is not empty %}
              <div class="formation-argument">
                <div class="formation-arguments_title">Liens utiles</div>
                {{ formation.links | markdown }}
              </div>
            {% endif %}
            <div class="formation-argument">
              <div class="formation-arguments_title">Informations</div>
              <ul>
                <li>{{ formation.duration | duration }} de vidéos</li>
                <li>{{ formation.courses.count }} chapitres</li>
              </ul>
            </div>
            {% if formation.secondaryTechnologies is not empty %}
              <div class="formation-argument">
                <div class="formation-arguments_title">Prérequis</div>
                <ul>
                  {% for technology in formation.secondaryTechnologies %}
                    <li><a href="{{ path(technology) }}">{{ technology.name }}</a></li>
                  {% endfor %}
                </ul>
              </div>
            {% endif %}
          </div>

          {% if first_course %}

            <progress-tracker contentId="{{ first_course.id }}" data-history="{{ first_course.id }}"
                              duration="{{ first_course.duration }}">
              <youtube-player
                id="course-{{ first_course.id }}"
                video="{{ first_course.youtubeId }}"
                poster="{{ image_url(first_course.image) }}"
                duration="{{ first_course.duration | duration }}"
                button="#chapter{{ first_course.id }} play-button"
                class="shadow formation-intro"></youtube-player>
            </progress-tracker>

          {% endif %}

        </div>

      </div>
    </main>

  {% endcache %}

  {{ show_history(formation.courses.toArray) }}

{% endblock %}

{% block javascripts %}
  {% if is_granted('ADMIN') %}
    <script>
      window.grafikart = {
        EDIT_LINK: "{{ path('admin_formation_edit', {id: formation.id}) }}"
      }
    </script>
  {% endif %}
  {{ parent() }}
{% endblock %}

templates/formations/tree.html.twig
{% extends 'base.html.twig' %}

{% block body %}

  <div class="tree">
      <h1 class="h1 text-center mb2">Apprenez le développement web</h1>
      <div class="hero-text text-center mb3" style="max-width: 630px; margin-left: auto; margin-right: auto;">
        Apprenez les bases du développement web et apprenez pas à pas comment construire un site web complet.
      </div>
      &nbsp;
      {% include 'formations/_tree-card.html.twig' with {slug: 'html', cls: 'is-root'} %}
      <div class="tree-link"></div>
      {% include 'formations/_tree-card.html.twig' with {slug: 'css'} %}
      <div class="tree-link" id="wave-anchor"></div>
      {% include 'formations/_tree-card.html.twig' with {slug: 'upload-site'} %}
      <div class="tree-link"></div>
      {% include 'formations/_tree-card.html.twig' with {slug: 'apprendre-algorithmique'} %}
      <div class="tree-category has-video">
        Quel langage choisir ?
        <strong>Orientation</strong>
        <a href="https://www.youtube.com/watch?v=3yWEsqqyvp4" class="tree-play" data-youtube></a>
      </div>
      <div class="tree-split">
        <!-- FRONTEND -->
        <div class="tree-row">
          <div class="tree-category">Spécialisation <strong>Frontend</strong></div>
          {% include 'formations/_tree-card.html.twig' with {slug: 'debuter-javascript'} %}
          <div class="tree-link"></div>
          {% include 'formations/_tree-card.html.twig' with {slug: 'git'} %}
          <div class="tree-link"></div>
          {% include 'formations/_tree-card.html.twig' with {slug: 'webpack'} %}
          <div class="tree-category">
            Spécialisation
            <strong>Framework</strong>
          </div>
          <div class="tree-choices">
            {% for lang in ['react', 'vuejs'] %}
              <div class="tree-choice {% if lang == 'react' %}is-active{% endif %}" data-choice="{{ lang }}"
                   style="width: 50%">
                <img src="{{ uploads_path('icons/' ~ lang ~ '.svg') }}" alt="">
              </div>
            {% endfor %}
          </div>
          <div class="tree-hidden is-visible" id="tree-react">
            {% include 'formations/_tree-card.html.twig' with {slug: 'react'} %}
          </div>
          <div class="tree-hidden" id="tree-vuejs">
            {% include 'formations/_tree-card.html.twig' with {slug: 'vuejs'} %}
          </div>
        </div>

        <!-- BACKEND -->
        <div class="tree-row">
          <div class="tree-category">Spécialisation <strong>backend</strong></div>
          <div class="tree-choices">
            {% for lang in ['php', 'ruby', 'nodejs'] %}
              <div class="tree-choice {% if lang == 'php' %}is-active{% endif %}" data-choice="{{ lang }}"
                   style="width: 50%">
                <img src="{{ uploads_path('icons/' ~ lang ~ '.svg') }}" alt="">
              </div>
            {% endfor %}
          </div>

          <!-- PHP -->
          <div class="tree-hidden is-visible" id="tree-php">
            {% include 'formations/_tree-card.html.twig' with {slug: 'php'} %}
            <div class="tree-link"></div>
            {% include 'formations/_tree-card.html.twig' with {slug: 'mysql'} %}
            <div class="tree-link"></div>
            {% include 'formations/_tree-card.html.twig' with {slug: 'programmation-objet-php'} %}
            <div class="tree-link"></div>
            {% include 'formations/_tree-card.html.twig' with {slug: 'git'} %}
            <div class="tree-category has-video">
              Quel framework choisir ?
              <strong>Orientation</strong>
              <a href="https://www.youtube.com/watch?v=tdZtQsu821M" class="tree-play" data-youtube></a>
            </div>
            <div class="tree-choices">
              {% for lang in ['symfony', 'laravel'] %}
                <div class="tree-choice {% if lang == 'symfony' %}is-active{% endif %}" style="width: 50%;" data-choice="{{ lang }}">
                  <img src="{{ uploads_path('icons/' ~ lang ~ '.svg') }}" alt="">
                </div>
              {% endfor %}
            </div>
            <div class="tree-hidden" id="tree-laravel">
              {% include 'formations/_tree-card.html.twig' with {slug: 'laravel'} %}
            </div>
            <div class="tree-hidden is-visible" id="tree-symfony">
              {% include 'formations/_tree-card.html.twig' with {slug: 'symfony-4-pratique'} %}
            </div>
          </div>

          <!-- Ruby -->
          <div class="tree-hidden" id="tree-ruby">
            {% include 'formations/_tree-card.html.twig' with {slug: 'ruby'} %}
            <div class="tree-link"></div>
            {% include 'formations/_tree-card.html.twig' with {slug: 'mysql'} %}
            <div class="tree-link"></div>
            {% include 'formations/_tree-card.html.twig' with {slug: 'ruby-on-rails'} %}
            <div class="tree-link"></div>
            {% include 'formations/_tree-card.html.twig' with {slug: 'git'} %}
          </div>

          <!-- Nodejs -->
          <div class="tree-hidden" id="tree-nodejs">
            {% include 'formations/_tree-card.html.twig' with {slug: 'debuter-javascript'} %}
            <div class="tree-link"></div>
            {% include 'formations/_tree-card.html.twig' with {slug: 'nodejs'} %}
            <div class="tree-link"></div>
            {% include 'formations/_tree-card.html.twig' with {slug: 'git'} %}
          </div>
        </div>
      </div>

  </div>

  <script>
    (function () {

      Array.from(document.querySelectorAll('.tree-choices')).forEach($choices => {
        let choices = $choices.querySelectorAll('.tree-choice')
        let activeChoice = $choices.querySelector('.is-active')
        let active = false
        if (activeChoice) {
          active = document.querySelector('#tree-' + activeChoice.dataset.choice)
        }
        Array.from(choices).forEach(function (choice) {
          choice.addEventListener('click', function () {
            if (active) {
              $choices.querySelector('.tree-choice.is-active').classList.remove('is-active')
              active.classList.remove('is-visible')
            }
            choice.classList.add('is-active')
            active = document.querySelector('#tree-' + choice.dataset.choice)
            active.classList.add('is-visible')
          })
        })
      })

      class Youtube {

        static init () {
          this.element = null
          document.querySelectorAll('[data-youtube]').forEach(link => {
            link.addEventListener('click', (e) => {
              e.preventDefault()
              this.onClick(link)
            })
          })
        }

        static onClick (link) {
          let youtubeID = link.getAttribute('href').split('=')[1]
          this.element = this.popup(youtubeID)
          document.body.appendChild(this.element)
        }

        static close () {
          this.element.parentNode.removeChild(this.element)
          this.element = null
        }

        static popup (youtube) {
          let element = document.createElement('div')
          element.classList.add('youtube-popup')
          element.innerHTML = `<div class="youtube-popup__close">
          <svg class="icon icon-user">
            <use xlink:href="/sprite.svg#cross"></use>
          </svg>
        </div>
      <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/${youtube}?autoplay=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`
          element.querySelector('.youtube-popup__close').addEventListener('click', e => {
            e.preventDefault()
            this.close()
          })
          return element
        }

      }

      Youtube.init()
    })()
  </script>

{% endblock %}